info:
  name: Train model
  type: http
  seq: 2

http:
  method: GET
  url: http://localhost:8080/api/regression/trainNSAD?controlOnly=True
  params:
    - name: controlOnly
      value: "True"
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Pre prune
    request:
      url: http://localhost:8080/api/regression/trainNSAD?controlOnly=True
      method: GET
      params:
        - name: controlOnly
          value: "True"
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: content-type
          value: application/json
        - name: transfer-encoding
          value: chunked
        - name: date
          value: Wed, 27 May 2026 10:01:39 GMT
        - name: keep-alive
          value: timeout=60
        - name: connection
          value: keep-alive
      body:
        type: json
        data: |-
          {
            "hyperParameters": {
              "numIterations": 225,
              "learningRate": 0.06,
              "maxDepth": 2,
              "minInstancesPerNode": 4,
              "subSamplingRate": 0.87,
              "maxBins": 32,
              "minInfoGain": 0.01
            },
            "meanSquaredError": 350.1173700494917,
            "featureImportance": {
              "FP1 Position": 0.18326983693604132,
              "SQ Position": 0.14183365708221415,
              "4-Race Average": 0.13145902678899904,
              "FP3 Position": 0.10966746767666535,
              "Average Points": 0.09641702449340697,
              "Team ID": 0.08737023492091155,
              "FP2 Position": 0.08068665607079961,
              "Is Team": 0.036596089256327916,
              "Standard Deviation": 0.029365874119345433,
              "FP2 Gap": 0.02348133380549598,
              "Days Since First Race": 0.022363767259185957,
              "FP3 Laps Done": 0.013598643664993191,
              "FP1 Laps Done": 0.012890145134028235,
              "FP1 Gap": 0.0085055180560901,
              "FP2 Laps Done": 0.008432225744783762,
              "SQ Laps Done": 0.007676869713921844,
              "SQ Gap": 0.004876403615440298,
              "FP3 Gap": 0.001509225661349468,
              "Is Sprint": 0.0,
              "FP1 Available": 0.0,
              "SQ Available": 0.0,
              "FP2 Available": 0.0,
              "FP3 Available": 0.0
            }
          }
  - name: Post prune 1
    request:
      url: http://localhost:8080/api/regression/trainNSAD?controlOnly=True
      method: GET
      params:
        - name: controlOnly
          value: "True"
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: content-type
          value: application/json
        - name: transfer-encoding
          value: chunked
        - name: date
          value: Wed, 27 May 2026 10:24:58 GMT
        - name: keep-alive
          value: timeout=60
        - name: connection
          value: keep-alive
      body:
        type: json
        data: |-
          {
            "hyperParameters": {
              "numIterations": 225,
              "learningRate": 0.06,
              "maxDepth": 2,
              "minInstancesPerNode": 4,
              "subSamplingRate": 0.87,
              "maxBins": 32,
              "minInfoGain": 0.01
            },
            "meanSquaredError": 338.3542357612706,
            "featureImportance": {
              "FP1 Position": 0.18460280791537215,
              "Average Points": 0.1422469954259285,
              "SQ Position": 0.12069687505882216,
              "FP3 Position": 0.11676165721595166,
              "FP2 Position": 0.09936663697996012,
              "4-Race Average": 0.09530438265755097,
              "Is Team": 0.07805380159176048,
              "Team ID": 0.0475107316445506,
              "Standard Deviation": 0.030443949505972363,
              "FP3 Laps Done": 0.01810633464688714,
              "FP1 Laps Done": 0.01770275911594397,
              "Days Since First Race": 0.014250702161796903,
              "FP2 Gap": 0.012379746192002246,
              "SQ Laps Done": 0.008323907661010339,
              "SQ Gap": 0.004549678997483129,
              "FP2 Laps Done": 0.00448137472968283,
              "FP1 Gap": 0.004040042734908589,
              "FP3 Gap": 0.0011776157644159
            }
          }
  - name: Post prune 2
    request:
      url: http://localhost:8080/api/regression/trainNSAD?controlOnly=True
      method: GET
      params:
        - name: controlOnly
          value: "True"
          type: query
    response:
      status: 200
      statusText: OK
      headers:
        - name: content-type
          value: application/json
        - name: transfer-encoding
          value: chunked
        - name: date
          value: Wed, 27 May 2026 10:38:55 GMT
        - name: keep-alive
          value: timeout=60
        - name: connection
          value: keep-alive
      body:
        type: json
        data: |-
          {
            "hyperParameters": {
              "numIterations": 225,
              "learningRate": 0.06,
              "maxDepth": 2,
              "minInstancesPerNode": 4,
              "subSamplingRate": 0.87,
              "maxBins": 32,
              "minInfoGain": 0.01
            },
            "meanSquaredError": 346.3245235083989,
            "featureImportance": {
              "FP1 Position": 0.18604580086734782,
              "SQ Position": 0.1575273772583747,
              "4-Race Average": 0.14072058225379233,
              "FP3 Position": 0.11690968229695829,
              "Average Points": 0.11638663531818642,
              "FP2 Position": 0.10577080466651649,
              "Team ID": 0.0848549499658459,
              "Standard Deviation": 0.04041692351707101,
              "Is Team": 0.03302745432269733,
              "Days Since First Race": 0.018339789533209538
            }
          }
