info:
  name: Train model
  type: http
  seq: 2

http:
  method: GET
  url: http://localhost:8080/api/regression/trainNSAD
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: Best with Fp1 Data
    description: The best run with fp1 data. It took 4030.17s and was ran on the 15th May
    request:
      url: http://localhost:8080/api/regression/trainNSAD
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: content-type
          value: application/json
        - name: transfer-encoding
          value: chunked
        - name: date
          value: Fri, 15 May 2026 09:41:52 GMT
        - name: keep-alive
          value: timeout=60
        - name: connection
          value: keep-alive
      body:
        type: json
        data: |-
          {
            "hyperParameters": {
              "numIterations": 225,
              "learningRate": 0.055,
              "maxDepth": 2,
              "minInstancesPerNode": 2,
              "subSamplingRate": 0.925
            },
            "meanSquaredError": 256.1065823384972,
            "featureImportance": {
              "FP1 Position": 0.2934446822553064,
              "4-Race Average": 0.16857911128579678,
              "Team ID": 0.1562632533139778,
              "Average Points": 0.12640045734285682,
              "Standard Deviation": 0.07314319498138051,
              "FP1 Gap": 0.056618816048099534,
              "Days Since First Race": 0.037966186553547096,
              "Is Sprint": 0.03307195782143176,
              "FP1 Laps Done": 0.028933828409589038,
              "Is Team": 0.025578511988014266
            }
          }
